### ISSUE TITLE
How to disable SIP?

### ISSUE THREAD

**Issue by St0nehead** [chris1111/Catalina-Recovery-HD-Partition#5]
SIP can be disabled only if you boot in recovery mode.
To boot into recovery, i need to create recovery partition first.
Create recovery partition needs to disable SIP.

Hmmmm... any suggestions?

**Comment by chris1111** [comment]
Boot with Usb create Install Media

**Comment by St0nehead** [comment]
![IMG_2872](https://user-images.githubusercontent.com/5366101/159775331-429a19e4-1e8b-4f78-bb6a-6696956c5343.jpg)

**Comment by chris1111** [comment]
Apple change the rule again

**Comment by St0nehead** [comment]
After some deep exploration, found a solution:
1) Download macOS Sierra 10.12.6 and make installation media USB stick. 
*you can do it using InstallDiskCreator (https://macdaddy.io/InstallDiskCreator.zip)
2) Reboot your mac and hold down ‘⌥’ (alt/opt) key, then choose your USB bootable media 
3) Go to menu Utilities/Terminal. 4) Type ‘csrutil disable’ and press ‘enter’ 
5) Reboot your mac.
6) Enjoy!
